export default {
  LogoPackingListCustomer: require('./Logo-Packing-List-Customer.png'),
  LogoDakotaLandscape: require('./Logo-Dakota-Landscape.png'),
  LogoDakotaPotrait: require('./Logo-Dakota-Potrait.png'),
  LogoAbsent: require('./Logo-Absent.png'),
  LogoLetterOfAsign: require('./Logo-Letter-Of-Asign.png'),
  LogoScanLetterOfAsign: require('./Logo-Scan-Letter-Of-Assign.png'),
  // JANGAN DIHAPUS MASIH TERPAKAI
  // LogoBooking: require('./Logo-Booking.png'),
  LogoLoper: require('./Logo-Loper.png'),
  LogoGoods: require('./Logo-Goods.png'),
  NoPhoto: require('./No-Photo.png'),
  NoImage: require('./No-Image.png'),
  Cardboard: require('./Cardboard.jpg'),
  MascotNotFound: require('./Mascot-Dakota_5.png'),
  Android: require('./Android.png'),
  Contact: require('./Contact.png'),
  LogoFormAbsence: require('./Logo-Form-Absence.png'),
  LogoRiwayatCIS: require('./LogoRiwayatCIS.png'),
  LogoCheckpoint: require('./Logo-Checkpoint.png'),
  LogoFlashAuto: require('./Logo-Flash-Auto.png'),
  LogoFlashOff: require('./Logo-Flash-Off.png'),
  LogoFlashOn: require('./Logo-Flash-On.png'),
  LogoTorch: require('./Logo-Torch.png'),
  // JANGAN DIHAPUS MASIH TERPAKAI
  // LogoChangeWorkArea: require("./Logo-ChangeWorkArea.png"),
  LessItems: require('./Less-Items.png'),
  LogoApproved: require('./Logo-Approved.png'),
  LogoFormCIS: require('./Logo-Form-CIS.png'),
  LogoSaldoCuti: require('./Logo-Saldo-Cuti.png'),
  LogoSlipGaji: require('./Logo-Slip-Gaji.png'),
  LogoKepegawaian: require('./Logo-Kepegawaian.png'),
  LogoOperational: require('./Operational.png'),
  LogoBarcode: require('./Logo-Barcode.png'),
  UploadPhoto: require('./Upload-Photo.png'),
};
